(() => {
  'use strict';
  const { showToast, escapeHTML, loadJSON, saveJSON, t, COLLEGE_LIST_KEY, PLAN_KEY } = window.P2C;

  const stagePlans = {
    explore:{label:'Beginning to think about college',checkIn:'Within two weeks',my:['Write down academic interests, career ideas, and questions about college.','Review current classes and graduation requirements.','Identify three types of programs or majors to explore.'],research:['Learn the difference between two-year, four-year, public, and private colleges.','Start a list of colleges, programs, or training options.','Choose a date to review what you learned.'],questions:['Which programs connect to my interests and long-term goals?','What academic, financial, location, or family factors matter most to me?']},
    choose:{label:'Deciding where to apply',checkIn:'Within one week',my:['Create a preliminary list of colleges and programs.','Compare admission requirements, location, program fit, and cost.','Add at least one likely, target, and reach option when possible.'],research:['Use official college pages to confirm requirements and deadlines.','Record cost, transportation, housing, and student-support questions.','Set a date to narrow the list.'],questions:['Which colleges best match my academic and practical priorities?','What information is still missing before I decide where to apply?']},
    apply:{label:'Preparing applications',checkIn:'Within one week',my:['Finish or revise the personal statement and activity list.','Request transcripts and recommendation letters.','Complete applications in deadline order.'],research:['Review each application checklist and identify the next deadline.','Find the correct office or official page for missing requirements.','Save submission confirmations and portal updates.'],questions:['Which application is due first, and what is still incomplete?','Which office should I contact if a required item is missing?']},
    funding:{label:'Finding ways to pay for college',checkIn:'Within one week',my:['Create a scholarship and funding deadline tracker.','Collect college cost information and admission offers.','List application fees, deposits, and other known expenses.'],research:['Confirm eligibility and deadlines on official program pages.','Separate grants and scholarships from charges and remaining costs.','Write questions for the appropriate financial-aid or billing office.'],questions:['Which funding deadline comes next?','Which cost, condition, or renewal rule is still unclear?']},
    decide:{label:'Reviewing admission decisions',checkIn:'Within five days',my:['Gather every admission decision and response deadline.','Compare program fit, total cost, location, and support services.','Write down the advantages and concerns for each option.'],research:['Create a side-by-side comparison of confirmed costs and aid.','Verify deposit deadlines and any conditions attached to an offer.','Contact the appropriate college office about unclear information.'],questions:['What is the remaining cost for each option?','Which college best matches my goals and practical needs?']},
    enroll:{label:'Preparing to enroll',checkIn:'Within one week',my:['Complete the enrollment response and deposit steps.','Register for orientation and courses.','Plan transportation, books, technology, housing, or other practical needs.'],research:['Create an enrollment checklist with dates and contacts.','Identify unresolved financial or administrative tasks.','Locate at least two campus support programs.'],questions:['What is my next required enrollment action and when is it due?','Which campus office should I contact before classes begin?']},
    support:{label:'Enrolled and seeking support',checkIn:'Within one week',my:['Identify the most urgent academic, financial, or personal concern.','Review course, advising, tutoring, and campus-support information.','Choose one office or program to contact this week.'],research:['Find the campus resource that matches the concern.','Prepare questions before making contact.','Record the response and next follow-up date.'],questions:['What immediate barrier is affecting my ability to continue?','Which campus program can provide ongoing support?']}
  };

  const adjustments = {
    start:{my:'Choose one manageable task that can be completed in the next 48 hours.',research:'Read the process in plain language and narrow the plan to three immediate priorities.',question:'What would make my next step feel clear and manageable?'},
    firstgen:{my:'Write down unfamiliar terms or instructions that need explanation.',research:'Use the glossary and official college pages to define each unfamiliar step.',question:'Which part of the process is least familiar to me or my family?'},
    fees:{my:'List each application-related fee and its due date.',research:'Find the published fee-waiver procedure and the correct office for questions.',question:'Who can confirm whether a fee waiver is available and what is required?'},
    time:{my:'Identify two realistic 20–30 minute work periods during the week.',research:'Break the plan into smaller tasks and add buffer time before deadlines.',question:'Which responsibilities must my plan work around?'},
    deadlines:{my:'Place all known deadlines in one calendar and highlight the earliest date.',research:'Prioritize tasks by consequence and set two reminders before the next deadline.',question:'Which deadline has the greatest consequence if missed?'},
    cost:{my:'Gather admission offers and cost information in one place.',research:'Separate grants and scholarships from charges, expected payments, and remaining balances.',question:'Which parts of the college offer are guaranteed, renewable, or still unclear?'},
    missing:{my:'Record each missing item, the office contacted, and the follow-up date.',research:'Create a missing-materials tracker and prepare a concise follow-up message.',question:'What does the application portal show, and who can confirm receipt?'},
    transition:{my:'List every remaining enrollment step and its deadline.',research:'Build a transition checklist covering orientation, registration, transportation, technology, and campus support.',question:'What is the next required action after accepting the offer?'}
  };

  const els={form:document.querySelector('#planner-form'),stage:document.querySelector('#stage-select'),challenge:document.querySelector('#challenge-select'),label:document.querySelector('#plan-stage-label'),my:document.querySelector('#my-task-list'),research:document.querySelector('#research-task-list'),questions:document.querySelector('#question-list'),checkIn:document.querySelector('#check-in-label'),date:document.querySelector('#check-in-date'),progressText:document.querySelector('#progress-text'),progressBar:document.querySelector('#progress-bar'),save:document.querySelector('#save-plan'),print:document.querySelector('#print-plan'),reset:document.querySelector('#reset-plan'),context:document.querySelector('#college-list-context'),contextSummary:document.querySelector('#college-context-summary'),contextChips:document.querySelector('#college-context-chips')};

  function getCollegeState(){return loadJSON(COLLEGE_LIST_KEY, loadJSON('pathwayToCollegeListV1',{profile:{},colleges:[]}));}
  function connectedPlan(stage, base){
    const state=getCollegeState(); const colleges=state?.colleges || [];
    if (!colleges.length || !['choose','apply','decide','funding'].includes(stage)) return base;
    const missing=colleges.find(c=>!c.deadline || !c.cost || !c.support);
    const nearest=colleges.filter(c=>c.deadline).sort((a,b)=>a.deadline.localeCompare(b.deadline))[0];
    const counts=colleges.reduce((x,c)=>{const k=(c.category||'').toLowerCase(); if(k in x)x[k]++; return x;},{likely:0,target:0,reach:0});
    const my=[...base.my], research=[...base.research], questions=[...base.questions];
    if(missing){my[0]=`Research missing deadline, cost, or support details for ${missing.name}.`;research[0]=`Find the official page or office that can confirm the missing information for ${missing.name}.`;}
    if(nearest){my[1]=`Confirm the application requirements for ${nearest.name}, the earliest dated option on the saved list.`;questions.unshift(`What is still incomplete for ${nearest.name}?`);}
    if(!counts.likely){my[2]='Add at least one attainable and affordable likely option to the college list.';research[1]='Search for a likely option that still meets my academic and support priorities.';}
    return {...base,my,research,questions};
  }
  function getPlan(stage,challenge){const base=stagePlans[stage]||stagePlans.apply;const a=adjustments[challenge]||adjustments.start;return connectedPlan(stage,{label:base.label,checkIn:base.checkIn,my:[base.my[0],base.my[1],a.my],research:[base.research[0],base.research[1],a.research],questions:[...base.questions,a.question]});}
  function taskMarkup(items,prefix,checked={}){return items.map((item,i)=>{const id=`${prefix}-${i}`;return `<label class="task-item" for="${id}"><input id="${id}" data-task-id="${id}" type="checkbox" ${checked[id]?'checked':''}/><span>${escapeHTML(t(item))}</span></label>`;}).join('');}
  function renderContext(){const state=getCollegeState();const colleges=state?.colleges||[];if(!colleges.length){els.context.hidden=true;return;}els.context.hidden=false;els.contextSummary.textContent=colleges.length===1?t('1 saved college is connected to this device. The plan can use missing details, deadlines, and list balance to shape next steps.'):t('{count} saved colleges are connected to this device. The plan can use missing details, deadlines, and list balance to shape next steps.',{count:colleges.length});els.contextChips.innerHTML=colleges.map(c=>`<span>${escapeHTML(c.name)} · ${escapeHTML(t(c.category||'Target'))}</span>`).join('');}
  function updateProgress(){const tasks=[...document.querySelectorAll('[data-task-id]')];const done=tasks.filter(x=>x.checked).length;els.progressText.textContent=t('{done} of {total} completed',{done,total:tasks.length});els.progressBar.style.width=tasks.length?`${Math.round(done/tasks.length*100)}%`:'0%';}
  function render(options={}){const stage=options.stage||els.stage.value;const challenge=options.challenge||els.challenge.value;if(options.stage)els.stage.value=stage;if(options.challenge)els.challenge.value=challenge;const plan=getPlan(stage,challenge);if(window.P2C.getLanguage()!=='en'){plan.my=['Review your goals and the next deadline.','Organize required documents and questions.','Complete one manageable task this week.'];plan.research=['Use official college pages to confirm current information.','Write down the office or person to contact.','Set a target date for follow-up.'];plan.questions=['What is my most urgent deadline?','What information or document is missing?','Who should I contact next?'];}const checked=options.checked||{};els.label.textContent=t(plan.label);els.my.innerHTML=taskMarkup(plan.my,'my',checked);els.research.innerHTML=taskMarkup(plan.research,'research',checked);els.questions.innerHTML=plan.questions.map(q=>`<li>${escapeHTML(t(q))}</li>`).join('');els.checkIn.textContent=t(plan.checkIn);renderContext();updateProgress();}
  function state(){const checked={};document.querySelectorAll('[data-task-id]').forEach(x=>checked[x.dataset.taskId]=x.checked);return{stage:els.stage.value,challenge:els.challenge.value,checked,date:els.date.value};}
  function save(show=true){const ok=saveJSON(PLAN_KEY,state());if(show)showToast(ok?'Action plan saved on this device.':'This browser could not save the plan.');}
  function load(){const old=loadJSON('pathwayToCollegePlanV1',null);const saved=loadJSON(PLAN_KEY,old||null);const params=new URLSearchParams(location.search);const queryStage=params.get('stage');const queryChallenge=params.get('challenge');if(saved){render({...saved,stage:queryStage||saved.stage,challenge:queryChallenge||saved.challenge});els.date.value=saved.date||'';}else{render({stage:queryStage||'apply',challenge:queryChallenge||'start'});}if(params.get('from')==='list')showToast('Saved college list connected to the action plan.');}
  els.form.addEventListener('submit',e=>{e.preventDefault();render();save(false);showToast('Action plan updated.');});
  document.addEventListener('change',e=>{if(e.target.matches('[data-task-id]')){updateProgress();save(false);}if(e.target===els.date)save(false);});
  els.save.addEventListener('click',()=>save(true));els.print.addEventListener('click',()=>window.print());els.reset.addEventListener('click',()=>{localStorage.removeItem(PLAN_KEY);els.stage.value='apply';els.challenge.value='start';els.date.value='';render();showToast('Saved plan reset.');});
  document.addEventListener('p2c:languagechange',()=>{const current=state();render(current);els.date.value=current.date||'';});
  load();
})();
