(() => {
  'use strict';
  const { t, escapeHTML } = window.P2C;
  const data = {
    explore:{period:'Junior year',title:'Explore and prepare',summary:'Use this stage to understand postsecondary options and establish a manageable starting point.',actions:['Consider interests, strengths, and possible fields of study.','Review graduation requirements and current academic progress.','Begin a list of colleges, programs, or training pathways.'],research:['Learn the major postsecondary pathways.','Write research questions for each option.','Set a date to review the first college list.'],materials:['Unofficial transcript or course list','Activities and interests','Questions about college vocabulary'],prompts:['What would you like college to make possible?','What practical factors matter most to you and your family?']},
    summer:{period:'Summer before senior year',title:'Build application materials',summary:'Create the core documents and systems that will make the fall application period easier to manage.',actions:['Draft the personal statement.','Create an activity list or résumé.','Identify potential recommenders.'],research:['Build an application calendar.','Review drafts for clarity and completeness.','Prepare clear recommendation requests.'],materials:['Essay drafts','Activity list','College list and requirements'],prompts:['Which experience best shows your goals or growth?','Which applications can be prepared early?']},
    fall:{period:'Fall application period',title:'Submit applications',summary:'Complete applications in deadline order and confirm that every required document has been received.',actions:['Complete forms and essays.','Request transcripts and recommendations.','Save confirmations and monitor portals.'],research:['Prioritize applications by deadline.','Review missing materials and fee-waiver questions.','Set reminders before major submission dates.'],materials:['Application accounts','Transcript and recommendation status','Submission confirmations'],prompts:['Which application is due first?','What is still incomplete or unclear?']},
    winter:{period:'Winter application period',title:'Complete funding steps',summary:'Continue scholarship and college funding work while monitoring submitted applications.',actions:['Track scholarship deadlines.','Review college messages and portals.','Collect cost and aid information.'],research:['Maintain a funding tracker.','Prepare questions for college staff.','Follow up on missing documents or unresolved requirements.'],materials:['Scholarship list','College cost estimates','Financial questions'],prompts:['Which funding deadline comes next?','Which eligibility question requires institution-specific confirmation?']},
    spring:{period:'Admission-decision period',title:'Compare decisions',summary:'Review admission offers, full costs, program fit, and required response dates side by side.',actions:['Gather every offer and deadline.','List the advantages and concerns for each option.','Identify unclear costs or conditions.'],research:['Build a comparison table.','Separate confirmed aid from remaining costs.','Prepare follow-up questions and flag decision deadlines.'],materials:['Admission letters','Aid and cost information','Deposit and response dates'],prompts:['What is the remaining cost for each option?','Which college best supports your academic and personal priorities?']},
    preenrollment:{period:'Enrollment preparation',title:'Complete the transition',summary:'Turn an admission choice into a practical enrollment and first-semester plan.',actions:['Complete the enrollment response and deposit steps.','Register for orientation and courses.','Plan transportation, books, technology, or housing.'],research:['Create an enrollment checklist.','Identify unresolved administrative or financial tasks.','Locate campus support programs.'],materials:['Enrollment portal','Orientation and registration information','First-semester support contacts'],prompts:['What is the next required action?','Which campus office should you contact before classes begin?']},
    semester:{period:'First college semester',title:'Stay connected',summary:'Use academic, financial, and community resources early rather than waiting for a crisis.',actions:['Learn how to contact advisers and tutoring services.','Review course and financial deadlines.','Identify a campus community or support program.'],research:['Use campus-based assistance early.','Prepare questions for the correct office.','Record the next contact and follow-up date.'],materials:['Course schedule','Campus support directory','Important semester dates'],prompts:['What is the most urgent barrier right now?','Which campus relationship can provide continuing support?']}
  };
  const els={period:document.querySelector('#timeline-detail-period'),title:document.querySelector('#timeline-detail-title'),summary:document.querySelector('#timeline-detail-summary'),actions:document.querySelector('#timeline-student-actions'),research:document.querySelector('#timeline-research-actions'),materials:document.querySelector('#timeline-materials'),prompts:document.querySelector('#timeline-prompts')};
  const list=items=>items.map(item=>`<li>${escapeHTML(t(item))}</li>`).join('');
  function render(key){const item=data[key]||data.explore;const translated=window.P2C.getLanguage()!=='en';const actions=translated?['Review your goals and the next deadline.','Organize required documents and questions.','Complete one manageable task this week.']:item.actions;const research=translated?['Use official college pages to confirm current information.','Write down the office or person to contact.','Set a target date for follow-up.']:item.research;const materials=translated?['Deadlines and dates','Required documents','Questions to answer']:item.materials;const prompts=translated?['What comes next?','What support do I need?']:item.prompts;els.period.textContent=t(item.period);els.title.textContent=t(item.title);els.summary.textContent=translated?t('Review your goals and the next deadline.'):t(item.summary);els.actions.innerHTML=list(actions);els.research.innerHTML=list(research);els.materials.innerHTML=list(materials);els.prompts.innerHTML=list(prompts);document.querySelectorAll('[data-timeline]').forEach(tab=>{const active=tab.dataset.timeline===key;tab.classList.toggle('active',active);tab.setAttribute('aria-selected',String(active));});}
  let current='explore';
  document.querySelectorAll('[data-timeline]').forEach(tab=>tab.addEventListener('click',()=>{current=tab.dataset.timeline;render(current);}));
  document.addEventListener('p2c:languagechange',()=>render(current));
  render(current);
})();
